### ISSUE TITLE
Proposed naming convention for gitbook repositories

### ISSUE THREAD

**Issue by GenevieveBuckley** [monashmicroimaging/gitbook-fiji-training#1]
I think we should have a common naming scheme for all the gitbook training materials, using the preface "gitbook-". Eg: gitbook-fiji-training, gitbook-imaris-training, gitbook-template. 

This will make it easier for other MMI people to find them in the whole list of repositories, and hopefully more likely to contribute.

**Comment by keithschulze** [comment]
Sounds good to me.

**Comment by GenevieveBuckley** [comment]
Done.
